### ISSUE TITLE
public key is not available: NO_PUBKEY 9334A25F8507EFA5

### ISSUE THREAD

**Issue by lwu001** [DemacMedia/vagrant-lamp#1]
First time user of vagrant with Virtualbox.

 Getting the following error when performing vagrant up.

==> demacvm: GPG error: http://repo.percona.com trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9334A25F8507EFA5
==> demacvm: + echo 'percona-server-server-5.6 percona-server-server/root_password password root'
==> demacvm: + sudo debconf-set-selections
==> demacvm: + echo 'percona-server-server-5.6 percona-server-server/root_password_again password root'
==> demacvm: + sudo debconf-set-selections
==> demacvm: + apt-get install -y percona-server-server-5.6 percona-server-client-5.6
==> demacvm: Reading package lists...
==> demacvm: Building dependency tree...
==> demacvm: Reading state information...
==> demacvm: The following extra packages will be installed:
==> demacvm:   libaio1 libdbd-mysql-perl libdbi-perl libperconaserverclient18.1
==> demacvm:   percona-server-common-5.6
==> demacvm: Suggested packages:
==> demacvm:   libclone-perl libmldbm-perl libnet-daemon-perl libplrpc-perl
==> demacvm:   libsql-statement-perl tinyca
==> demacvm: The following NEW packages will be installed:
==> demacvm:   libaio1 libdbd-mysql-perl libdbi-perl libperconaserverclient18.1
==> demacvm:   percona-server-client-5.6 percona-server-common-5.6
==> demacvm:   percona-server-server-5.6
==> demacvm: 0 upgraded, 7 newly installed, 0 to remove and 1 not upgraded.
==> demacvm: Need to get 14.3 MB of archives.
==> demacvm: After this operation, 139 MB of additional disk space will be used.
==> demacvm: WARNING: The following packages cannot be authenticated!
==> demacvm:   percona-server-common-5.6 libperconaserverclient18.1
==> demacvm:   percona-server-client-5.6 percona-server-server-5.6
==> demacvm: E
==> demacvm: :
==> demacvm: There are problems and -y was used without --force-yes
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I think the percona key has changed since this package was created. I'm not sure how to correct it. Any assistance is welcomed.

Thanks.

**Comment by reztierk** [comment]
Thanks for letting us know about the issue, just pushed an update that should resolve it.
